In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# unzip dataset from Google Drive
import zipfile

zip_path = '/content/drive/MyDrive/Colab Notebooks/developer recruitment questionnaire_2025/stack-overflow-developer-survey-2025.zip'
extract_path = '/content/stack_overflow_data'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [4]:
import os

# check extracted files
os.listdir('/content/stack_overflow_data')

['survey_results_schema.csv',
 'survey_results_public.csv',
 '2025_Developer_Survey_Tool.pdf']

In [5]:
import pandas as pd

In [6]:
# show all columns
pd.set_option('display.max_columns', None)

In [7]:
# load main dataset
df = pd.read_csv('/content/stack_overflow_data/survey_results_public.csv')
# load dataset schema
schema = pd.read_csv('/content/stack_overflow_data/survey_results_schema.csv')

df

/tmp/ipykernel_1702/450902754.py:2: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/stack_overflow_data/survey_results_public.csv')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [8]:
# show column names
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [9]:
# check data types and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [10]:
# get total number of rows
df.shape[0]

49191

In [11]:
# check unique respondents
df['ResponseId'].nunique()

49191

In [12]:
# check duplicates
df['ResponseId'].duplicated().sum()

np.int64(0)

**1. Total number of respondents**

In [13]:
# total number of respondents
df['ResponseId'].nunique()

49191

**2. Response completeness analysis**

In [14]:
# inspect survey schema table
schema

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [15]:
schema['qname']

0        TechEndorse_1
1        TechEndorse_2
2        TechEndorse_3
3        TechEndorse_4
4        TechEndorse_5
            ...
134    AIAgentObsWrite
135    AIAgentExternal
136    AIAgentExtWrite
137            AIHuman
138             AIOpen
Name: qname, Length: 139, dtype: object

In [16]:
# question types distribution
schema['type'].value_counts()

type
RO        49
MC        48
TE        29
Matrix    13
Name: count, dtype: int64

In [17]:
# get list of question names
questions = set(schema['qname'])

In [18]:
# keep only questions that exist in df
questions_in_df = list(questions.intersection(df.columns))

# preview matched questions
questions_in_df[:10]

['DatabaseHaveEntry',
 'YearsCode',
 'AIAgentOrchestration',
 'JobSatPoints_8',
 'RemoteWork',
 'JobSatPoints_9',
 'Employment',
 'AIOpen',
 'JobSatPoints_14',
 'LearnCodeAI']

In [19]:
# keep only respondents without missing values in all questio
full_answers = df.dropna(subset=questions_in_df)

In [20]:
# count respondents who answered all questions
full_answers.shape[0]

0

**3. Statistical analysis of respondents' work experience**

In [21]:
# inspect distribution of WorkExp (years of experience)
df['WorkExp']

0         8.0
1         2.0
2        10.0
3         4.0
4        21.0
         ...
49186     NaN
49187    25.0
49188    17.0
49189     2.0
49190     NaN
Name: WorkExp, Length: 49191, dtype: float64

In [22]:
# перевіремо кількість пропущених значень у WorkExp
df['WorkExp'].isna().sum()

np.int64(6298)

In [23]:
# remove missing values from WorkExp column
work_exp_clean = df['WorkExp'].dropna()

# cleaned data
work_exp_clean.isna().sum()

np.int64(0)

In [24]:
print("Mean:", work_exp_clean.mean())
print("Median:", work_exp_clean.median())
print("Mode:", work_exp_clean.mode().iloc[0])

Mean: 13.367402606485907
Median: 10.0
Mode: 10.0

**4. Remote work analysis**

In [25]:
df['RemoteWork']

0                                                   Remote
1        Hybrid (some in-person, leans heavy to flexibi...
2                                                      NaN
3                                                   Remote
4                                                      NaN
                               ...
49186                                                  NaN
49187                                                  NaN
49188    Hybrid (some in-person, leans heavy to flexibi...
49189                                                  NaN
49190                                                  NaN
Name: RemoteWork, Length: 49191, dtype: object

In [26]:
# unique work format values
df['RemoteWork'].unique()

array(['Remote', 'Hybrid (some in-person, leans heavy to flexibility)',
       nan, 'In-person', 'Hybrid (some remote, leans heavy to in-person)',
       'Your choice (very flexible, you can come in when you want or just as needed)'],
      dtype=object)

In [27]:
# keep only remote respondents
remote_workers = df[df['RemoteWork'] == 'Remote']

# count remote respondents
remote_workers.shape[0]

10931

In [28]:
# calculate percentage of remote respondents
remote_percent = (remote_workers.shape[0] / df.shape[0]) * 100

print("Remote percentage:", round(remote_percent, 2), "%")

Remote percentage: 22.22 %

**5. Python popularity analysis**

In [29]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [30]:
df['LanguageHaveWorkedWith']

0                         Bash/Shell (all shells);Dart;SQL
1                                                     Java
2                      Dart;HTML/CSS;JavaScript;TypeScript
3                                          Java;Kotlin;SQL
4        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
                               ...
49186                                                  NaN
49187                                                  NaN
49188                                                  NaN
49189                                                  NaN
49190                                                  NaN
Name: LanguageHaveWorkedWith, Length: 49191, dtype: object

In [31]:
# create a boolean flag for respondents who worked with Python
df['worked_with_python'] = df['LanguageHaveWorkedWith'].str.contains(
    'Python',
    case=False,
    na=False
)

df['worked_with_python']

0        False
1        False
2        False
3        False
4         True
         ...
49186    False
49187    False
49188    False
49189    False
49190    False
Name: worked_with_python, Length: 49191, dtype: bool

In [32]:
# count respondents who worked with Python
python_users = df['worked_with_python'].sum()

print("Python users:", python_users)

Python users: 18466

In [33]:
# calculate share of respondents who worked with Python
python_percent = (python_users / df.shape[0]) * 100

print("Python users share:", round(python_percent, 2), "%")

Python users share: 37.54 %

In [34]:
# define programming languages for comparison
languages = [
    'Python',
    'JavaScript',
    'SQL',
    'HTML/CSS',
    'TypeScript',
    'C++',
    'C#',
    'PHP',
    'Go',
    'Rust'
]

# count respondents for each language
for lang in languages:
    count = df['LanguageHaveWorkedWith'].str.contains(
        lang,
        case=False,
        na=False
    ).sum()

    print(lang, ":", count)

Python : 18466
JavaScript : 21005
SQL : 18633
HTML/CSS : 19698
TypeScript : 13859
C++ : 28262
C# : 8852
PHP : 5994
Go : 5219
Rust : 4724

**6. Learning paths analysis**

In [35]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchWrite', 'AIAgentObserveSecure', 'AIAgentObsWrite',
       'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman', 'AIOpen',
       'ConvertedCompYearly', 'JobSat', 'worked_with_python'],
      dtype='object', length=173)

In [36]:
# inspect learning methods column
df['LearnCode']

0        Online Courses or Certification (includes all ...
1        Online Courses or Certification (includes all ...
2        Online Courses or Certification (includes all ...
3        Other online resources (e.g. standard search, ...
4                                                      NaN
                               ...
49186                                                  NaN
49187    Online Courses or Certification (includes all ...
49188    Online Courses or Certification (includes all ...
49189    Videos (not associated with specific online co...
49190    Online Courses or Certification (includes all ...
Name: LearnCode, Length: 49191, dtype: object

In [37]:
# create a boolean flag for online courses
df['online_courses'] = df['LearnCode'].str.contains(
    'Online Courses',
    case=False,
    na=False
)

df['online_courses']

0         True
1         True
2         True
3        False
4        False
         ...
49186    False
49187     True
49188     True
49189    False
49190     True
Name: online_courses, Length: 49191, dtype: bool

In [38]:
# count respondents who learned through online courses
online_users = df['online_courses'].sum()

print("Online course users:", online_users)

Online course users: 10973

In [39]:
# check online course users count
df[df['online_courses'] == True].shape[0]

10973

In [40]:
# define popular learning methods for comparison
learn_methods = [
    'Online Courses',
    'Books',
    'School',
    'Colleague',
    'Friend or family member',
    'Other online resources',
    'Videos'
]

# count respondents for each learning method
for method in learn_methods:
    count = df['LearnCode'].str.contains(
        method,
        case=False,
        na=False
    ).sum()

    print(method, ":", count)

Online Courses : 10973
Books : 10187
School : 5561
Colleague : 8596
Friend or family member : 0
Other online resources : 19701
Videos : 16771

**7. Python developer compensation by country**

In [41]:
df['worked_with_python']

0        False
1        False
2        False
3        False
4         True
         ...
49186    False
49187    False
49188    False
49189    False
49190    False
Name: worked_with_python, Length: 49191, dtype: bool

In [42]:
# filter respondents who worked with Python
py_df = df[df['worked_with_python'] == True]


# keep only records with annual compensation data
py_df = py_df.dropna(subset=['ConvertedCompYearly'])

py_df.shape[0]

12765

In [43]:
# inspect country distribution for Python developers
py_df['Country']

4                         Ukraine
7                         Ukraine
8                         Ukraine
22       United States of America
27                         Sweden
                   ...
49028    United States of America
49088    United States of America
49089                       India
49105                       Egypt
49106                South Africa
Name: Country, Length: 12765, dtype: object

In [44]:
# inspect annual compensation column
py_df['ConvertedCompYearly']

4         60000.0
7         72000.0
8         70000.0
22        87500.0
27       209643.0
           ...
49028     77000.0
49088    280000.0
49089      4650.0
49105       719.0
49106     69008.0
Name: ConvertedCompYearly, Length: 12765, dtype: float64

In [45]:
# group by country and calculate average and median compensation
salary_by_country = py_df.groupby('Country')['ConvertedCompYearly'].agg(
    mean_salary='mean',
    median_salary='median'
)

salary_by_country.sort_values(by='mean_salary', ascending=False)

                            mean_salary  median_salary
Country
Oman                      390135.000000       390135.0
Andorra                   226103.500000       226103.5
Viet Nam                  218837.166667         8254.0
United States of America  173298.590211       150000.0
Switzerland               156456.600000       142592.0
...                                 ...            ...
Botswana                    1277.000000         1277.0
Cambodia                    1270.000000         1270.0
Togo                         354.000000          354.0
Palestine                     78.000000           78.0
Antigua and Barbuda            1.000000            1.0

[153 rows x 2 columns]

In [46]:
# check number of respondents by country
country_count = py_df.groupby('Country')['ConvertedCompYearly'].count()

country_count.sort_values(ascending=False)

Country
United States of America                                3126
Germany                                                 1188
United Kingdom of Great Britain and Northern Ireland     750
France                                                   588
India                                                    543
                                                        ...
Palestine                                                  1
Republic of Moldova                                        1
Qatar                                                      1
Togo                                                       1
Somalia                                                    1
Name: ConvertedCompYearly, Length: 153, dtype: int64

**8. Education profile of top-paid respondents**

In [47]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal',
       'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'ConvertedCompYearly', 'JobSat',
       'worked_with_python', 'online_courses'],
      dtype='object', length=174)

In [48]:
# inspect annual compensation column
df['ConvertedCompYearly']

0         61256.0
1        104413.0
2         53061.0
3         36197.0
4         60000.0
           ...
49186         NaN
49187         NaN
49188         NaN
49189         NaN
49190         NaN
Name: ConvertedCompYearly, Length: 49191, dtype: float64

In [49]:
# inspect education level column
df['EdLevel']

0          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
1                      Associate degree (A.A., A.S., etc.)
2             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3             Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4          Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
                               ...
49186         Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49187    Some college/university study without earning ...
49188      Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
49189       Professional degree (JD, MD, Ph.D, Ed.D, etc.)
49190    Some college/university study without earning ...
Name: EdLevel, Length: 49191, dtype: object

In [50]:
# keep records with valid compensation and education data
top_salary = df[['ConvertedCompYearly', 'EdLevel']].dropna()

top_salary

       ConvertedCompYearly                                            EdLevel
0                  61256.0    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
1                 104413.0                Associate degree (A.A., A.S., etc.)
2                  53061.0       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3                  36197.0       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4                  60000.0    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
...                    ...                                                ...
49098               2729.0     Professional degree (JD, MD, Ph.D, Ed.D, etc.)
49105                719.0  Some college/university study without earning ...
49106              69008.0       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
49121              58007.0                Associate degree (A.A., A.S., etc.)
49122              46406.0  Some college/university study without earning ...

[23930 rows x 2 columns]

In [51]:
# sort by compensation in descending order
top_salary = top_salary.sort_values(
    by='ConvertedCompYearly',
    ascending=False
)

top_salary

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
...                    ...                                              ...
8405                   1.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
48524                  1.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
47176                  1.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
90                     1.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
21034                  1.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

[23930 rows x 2 columns]

In [52]:
# select top 5 respondents by compensation
top_5_salary = top_salary.head(5)

top_5_salary

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

**9. Python usage analysis by age groups**

In [53]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal',
       'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'ConvertedCompYearly', 'JobSat',
       'worked_with_python', 'online_courses'],
      dtype='object', length=174)

In [54]:
# inspect age category column
df['Age']

0        25-34 years old
1        25-34 years old
2        35-44 years old
3        35-44 years old
4        35-44 years old
              ...
49186    18-24 years old
49187    45-54 years old
49188    35-44 years old
49189    25-34 years old
49190    18-24 years old
Name: Age, Length: 49191, dtype: object

In [55]:
# check unique age categories
df['Age'].unique()

array(['25-34 years old', '35-44 years old', '45-54 years old',
       '18-24 years old', '65 years or older', '55-64 years old',
       'Prefer not to say'], dtype=object)

In [56]:
# percentage of respondents who used Python by age group
python_by_age = round(
    df.groupby('Age')['worked_with_python'].mean() * 100,
    2
)

python_by_age

Age
18-24 years old      40.00
25-34 years old      36.94
35-44 years old      36.72
45-54 years old      38.63
55-64 years old      37.24
65 years or older    31.63
Prefer not to say    31.22
Name: worked_with_python, dtype: float64

**10. Industry analysis of top-paid remote workers**

In [57]:
# inspect compensation, work format, and industry columns
df[['ConvertedCompYearly', 'RemoteWork', 'Industry']]

,ConvertedCompYearly,RemoteWork,Industry
0,61256.0,Remote,Fintech
1,104413.0,"Hybrid (some in-person, leans heavy to flexibi...",Retail and Consumer Services
2,53061.0,NaN,Software Development
3,36197.0,Remote,Retail and Consumer Services
4,60000.0,NaN,Software Development
...,...,...,...
49186,NaN,NaN,NaN
49187,NaN,NaN,NaN
49188,NaN,"Hybrid (some in-person, leans heavy to flexibi...",Banking/Financial Services
49189,NaN,NaN,NaN
49190,NaN,NaN,NaN

In [58]:
salary_clean = df['ConvertedCompYearly'].dropna()

In [59]:
# calculate 75th percentile of compensation
salary_75 = salary_clean.quantile(0.75)

salary_75

np.float64(120596.0)

In [60]:
# filter top-paid remote workers
top_remote = df[
    (df['ConvertedCompYearly'] > salary_75) &
    (df['RemoteWork'] == 'Remote')
]

top_remote

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,worked_with_python,online_courses
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,15.0,"Developer, mobile",500 to 999 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,9.0,3.0,4.0,8.0,11.0,7.0,5.0,1.0,10.0,14.0,NaN,12.0,4.0,5.0,9.0,14.0,7.0,11.0,6.0,2.0,15.0,NaN,Software Development,7.0,6.0,9.0,10.0,11.0,12.0,13.0,5.0,14.0,8.0,1.0,3.0,4.0,15.0,2.0,NaN,No,I have neither consider or transitioned into a...,6.0,6.0,United States of America,USD United States dollar,205000.0,Yes,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,NaN,NaN,NaN,NaN,Yes,MySQL;PostgreSQL;SQLite;Supabase,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,NaN,NaN,NaN,Yes,Next.js;Node.js;React,NaN,NaN,"Remix, Capacitor, Ionic",NaN,Yes,Android Studio;Claude Code;Cursor;IntelliJ IDE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;Linux (non-WSL),Windows;MacOS;Android;Linux (non-WSL),GitHub;GitLab;Google Workspace;Jira;Notion;Tre...,NaN,NaN,NaN,NaN,Discord;Reddit;Hacker News;GitHub (public proj...,NaN,NaN,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Between 10 and 15 years,"Infrequently, less than once per year",Chat (bot/AI),10.0,NaN,9.0,6.0,1.0,5.0,13.0,12.0,8.0,15.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Very poor at handling complex tasks,Writing code;Learning new concepts or technolo...,Project planning;Deployment and monitoring;Pre...,Learning about a codebase;Testing code,Committing and reviewing code;Creating or main...,Documenting code;Debugging or fixing code;Sear...,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0,False,False
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,23.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,11.0,10.0,9.0,8.0,2.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,2.0,3.0,4.0,11.0,12.0,5.0,6.0,10.0,7.0,8.0,9.0,13.0,14.0,15.0,1.0,NaN,No,I have neither consider or transitioned into a...,5.0,8.0,United States of America,USD United States dollar,250000.0,Yes,Elixir;HTML/CSS;JavaScript;SQL;TypeScript,Elixir;HTML/CSS;OCaml;Gleam,Elixir;HTML/CSS,NaN,NaN,Yes,BigQuery;Elasticsearch;PostgreSQL;SQLite,SQLite,SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Datadog;D...,Cloudflare;Homebrew;Make,Cloudflare;Homebrew;Make,hex,hex,Yes,Node.js;Phoenix;React,Phoenix,Phoenix,NaN,NaN,Yes,NaN,NaN,NaN,emacs,emacs,Tailwind CSS 4;Large Language Model,Tailwind CSS 4,Tailwind CSS 4,NaN,NaN,MacOS,MacOS,Airtable;Confluence;GitHub;Google Workspace;Ji...,NaN,NaN,NaN,NaN,Reddit;Dev.to;Hacker News;GitHub (public proje...,"GitHub (public projects, not private repos);Sl...","GitHub (public projects, not private repos);Sl...",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0,False,False
41,42,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Transitioning to retirement (gradually reducin...,25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training;Online Course...,25.0,"Developer, front-end",Less than 20 employees,Individual contributor,Remote,No,Personal Project,4.0,2.0,12.0,7.0,6.0,11.0,8.0,5.0,1.0,14.0,NaN,12.0,1.0,9.0,4.0,5.0,3.0,8.0,7.0,2.0,15.0,NaN,Software Development,5.0,2.0,6.0,11.0,10.0,8.0,7.0,9.0,12.0,13.0,1.0,14.0,3.0,15.0,4.0,NaN,Yes,I have somewhat considered changing my career ...,3.0,2.0,United States of America,USD United States dollar,270000.0,Yes,HTML/CSS;JavaScript;Python;TypeScript,HTML/CSS;JavaScript;Python;TypeScript,HTML/CSS;JavaScript;Python;TypeScript,NaN,NaN,Yes,PostgreSQL,PostgreSQL,PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Datadog;Homebrew;npm;Vercel;Vite,Datadog;Homebrew;npm;Vercel;Vite,NaN,NaN,Yes,Next.js;Node.js;React;Svelte,Svelte,Svelte,NaN,NaN,Yes,Cursor,Cursor,Cursor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS;iOS,MacOS;Linux (non-WSL),GitHub;Linear;Notion,GitHub;Linear;Notion,GitHub;Linear;Notion,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,Anthropic: Claude Sonnet,Anthropic: Claude Sonnet,Anthropic: Claude Sonnet,NaN,NaN,Yes,A few times per week,"More than 15 years, or since Stack Overflow st...",A few times per month or weekly,Chat (people);Job board,10.0,NaN,8.0,9.0,1.0,4.0,14.0,11.0,5.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Favorable,Somewhat distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Project planning;Committing and reviewing code...,Deployment and monitoring;Creating or maintain...,Testing code,Generating content or synthetic data,"AI solutions that are almost right, but not qu...",No. Vibe coding is fine for demos but not prof...,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,I am concerned about the accuracy of the infor...,NaN,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Requirements gathering, big fixing",270000.0,3.0,True,True
42,43,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc....",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,35.0,"Developer, mobile","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Personal Project,8.0,3.0,2.0,6.0,7.0,1.0,5.0,4.0,9.0,14.0,NaN,8.0,1.0,6.0,2.0,4.0,9.0,7.0,13.0,14.0,15.0,NaN,Software Development,3.0,4.0,9.0,12.0,13.0,14.0,6.0,2.0,7.0,8.0,1.0,10.0,5.0,15.0,11.0,NaN,No,I have neither consider or transitioned into a...,10.0,10.0,United States of America,USD United States dollar,250000.0,Yes,Bash/Shell (all shells);C;C#;C++;HTML/CSS;Java...,Assembly;Go;Ruby;Rust,NaN,NaN,NaN,NaN,Microsoft SQL Server;MySQL;Oracle;SQLite,Cosmos DB;DuckDB;Dynamodb;IBM DB2;InfluxDB;Mon...,NaN,NaN,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,Yes,AngularJS;ASP.NET;ASP.NET Core;Django;jQuery;N...,Ruby on Rails;Spring Boot,Ruby on Rails,NaN,NaN,Yes,Android Studio;Claude Code;Eclipse;IntelliJ ID...,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Google Gemini,NaN,NaN,NaN,NaN,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Azure Devops;Coda;Doxygen;GitHub;GitLab;Google...,Airtable;Obsidian;Stack Overflow for Teams;Trello,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Company-sponsored forums,Company-sponsored forums,NaN,NaN,Yes,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Alibaba Cloud Qwen models;Amazon Titan models;...,Anthropic: Claude Sonnet,NaN,NaN,Yes,Daily or almost daily,Between 10 and 15 years,A few times per month or weekly,Message Boards;Long-form articles,9.0,NaN,6.0,2.0,4.0,1.0,8.0,7.0,11.0,15.0,NaN,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Very well at handling complex tasks,Documenting code;Generating content or synthet...,NaN,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Debuggi...,Other (write in):,Yes. Use it daily.,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,Language processing;Agent/multi-agent orchestr...,AI agents have increased my productivity.;AI a...,AI agents have improved collaboration within m...,NaN,AI agents have helped me automate repetitive t...,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis;ChromaDB,NaN,Llama Index;Ollama;OpenRouter,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I want to fully understand something;When...,Multiplatform Platform code conversion. Langua...,250000.0,8.0,True,True
48,49,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,21.0,"Senior executive (C-suite, VP, etc.)",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,12.0,1.0,10.0,9.0,4.0,2.0,14.0,NaN,14.0,6.0,11.0,10.0,1.0,2.0,5.0,9.0,3.0,15.0,NaN,Fintech,5.0,6.0,7.0,13.0,12.0,8.0,11.0,9.0,10.0,14.0,1.0,3.0,2.0,15.0,4.0,NaN,I'm not sure,I have somewhat considered changing my career ...,10.0,5.0,United Kingdom of Great Britain and Northern I...,GBP Pound sterling,105000.0,Yes,C#;Elixir;HTML/CSS;JavaScript;SQL;TypeScript,C#;Elixir;HTML/CSS;SQL,C#;Elixir;HTML/CSS;SQL,Haskell,NaN,Yes,Cosmos DB;Elasticsearch;Microsoft SQL Server;P...,Cosmos DB;Microsoft SQL Server;PostgreSQL,Cosmos DB;Microsoft SQL Server;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Docker;Go...,Amazon Web Services (AWS);Cloudflare;Docker;Mi...,Amazon Web Services (AWS);Cloudflare;Docker;Mi...,NaN,NaN,Yes,ASP.NET Core;Next.js;Phoenix,ASP.NET Core;Blazor;Phoenix,ASP.NET Core;Phoenix,NaN,Ash,Yes,Aider;Claude Code;Cursor;Jupyter Notebook/Jupy...,Jupyter Notebook/JupyterLab;Neovim;Rider;Visua...,Jupyter Notebook/JupyterLab;Neovim;Rider;Visua...,NaN,NaN,Tailwind CSS 4;Large Language Model;Shadcn/ui,Tailwind CSS 4;Microsoft Fabric;Shadcn/ui,Tailwind CSS 4;Shadcn/ui,NaN,NaN,Windows;MacOS;iOS,MacOS;Ubuntu;Linux (non-WSL),Azure Devops;Confluence;GitHub;Google Workspac...,GitHub;Google Workspace;Lucid (includes Lucidc...,GitHub;Google Workspace;Notion,Whimsical,Whimsical,Stack Overflow;Reddit;Hacker News;GitHub (publ...,Stack Overflow;Discord;Reddit;Hacker News;GitH...,Stack Overflow;Reddit;Hacker News;GitHub (publ...,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet;Gemini (Pro Reasoning...,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",Long-form articles;Coding challenges;Lists of ...,9.0,NaN,10.0,6.0,1.0,2.0,8.0,11.0,14.0,15.0,NaN,"Yes, somewhat",Less than half of the time,"Yes, I use AI tools monthly or infrequently",Unfavorable,Highly distrust,Very poor at handling complex tasks,Writing code;Debugging or fixing code;Learning...,Project planning;Documenting code;Deployment a...,Learning about a codebase;Testing code;Committ...,Generating content or synthetic data,NaN,"AI solutions that are almost right, but not qu...",No,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,My company's IT and/or InfoSec teams have stri...,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"Problem solving and reasoning, unless we get f...",142949.0,7.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48913,48914,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,20.0,"Developer, mobile",Less than 20 employees,Individual contributor,Remote,No,Personal Project,8.0,2.0,3.0,9.0,5.0,6.0,7.0,4.0,1.0,10.0,NaN,9.0,6.0,2.0,7.0,1.0,4.0,3.0,5.0,8.0,10.0,NaN,Software Development,9.0,3.0,12.0,2.0,5.0,14.0,10.0,4.0,8.0,13.0,1.0,11.0,6.0,15.0,7.0,NaN,I'm not sure,I have neither consider or transitioned into a...,10.0,10.0,United Kingdom of Great Britain and Northern I...,GBP Pound sterling,95000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,"More than 15 years, or since Stack Overflow st...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129334.0,9.0,False,False

In [61]:
# inspect industry column for selected respondents
top_remote['Industry']

29               Software Development
31                            Fintech
41               Software Development
42               Software Development
48                            Fintech
                     ...
48913            Software Development
48937    Retail and Consumer Services
48970                      Healthcare
49083    Retail and Consumer Services
49088            Software Development
Name: Industry, Length: 2461, dtype: object

In [62]:
# count most common industries
industry_count = top_remote['Industry'].value_counts()

industry_count

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64

In [63]:
# select top 10 industries
industry_top10 = industry_count.head(10)

industry_top10

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Name: count, dtype: int64

In [64]:
# export top 10 industries to CSV file
industry_top10.to_csv('industry_top10.csv')

In [65]:
import os

os.listdir()

['.config',
 'drive',
 'industry_top10.csv',
 'stack_overflow_data',
 'sample_data']

In [66]:
import pandas as pd
# define programming languages for comparison
languages = [
    'Python',
    'JavaScript',
    'SQL',
    'HTML/CSS',
    'TypeScript',
    'C++',
    'C#',
    'PHP',
    'Go',
    'Rust'
]

language_counts = []
# count respondents for each language
for lang in languages:
    count = df['LanguageHaveWorkedWith'].str.contains(
        lang,
        case=False,
        na=False
    ).sum()

    language_counts.append([lang, count])
# create and sort language popularity table
languages_top10 = pd.DataFrame(
    language_counts,
    columns=['Language', 'Count']
)

languages_top10 = languages_top10.sort_values(
    by='Count',
    ascending=False
).reset_index(drop=True)

languages_top10

     Language  Count
0         C++  28262
1  JavaScript  21005
2    HTML/CSS  19698
3         SQL  18633
4      Python  18466
5  TypeScript  13859
6          C#   8852
7         PHP   5994
8          Go   5219
9        Rust   4724

In [67]:
# export top 10 programming languages to CSV
languages_top10.to_csv('languages_top10.csv', index=False)

In [68]:
top_remote.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal',
       'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'ConvertedCompYearly', 'JobSat',
       'worked_with_python', 'online_courses'],
      dtype='object', length=174)

In [69]:
# calculate Python popularity (%) and number of respondents in each age group
python_by_age_table = (
    df.groupby('Age')
    .agg(
        Python_percent=('worked_with_python', lambda x: round(x.mean() * 100, 2)),
        Respondents=('worked_with_python', 'count')
    )
    .reset_index()
)

# preview the final table before exporting to Tableau
python_by_age_table

                 Age  Python_percent  Respondents
0    18-24 years old           40.00         9210
1    25-34 years old           36.94        16519
2    35-44 years old           36.72        13241
3    45-54 years old           38.63         6275
4    55-64 years old           37.24         2626
5  65 years or older           31.63          942
6  Prefer not to say           31.22          378

In [70]:
# export Python usage by age groups to CSV
python_by_age_table.to_csv('python_by_age.csv', index=False)

In [71]:
# calculate median salary and number of respondents by country

country_stats = py_df.groupby('Country')['ConvertedCompYearly'].agg(
    median_salary='median',
    respondents='count'
)

# filter countries with at least 30 respondents

country_stats = country_stats[
    country_stats['respondents'] >= 30
]

# sort countries by median salary in descending order
# select top 10 countries

country_stats = country_stats.sort_values(
    by='median_salary',
    ascending=False
).head(10)

country_stats

                                                    median_salary  respondents
Country
United States of America                                 150000.0         3126
Israel                                                   142594.0          104
Switzerland                                              142592.0          240
Ireland                                                  116015.0           74
Denmark                                                   98289.0          120
Australia                                                 97514.0          307
United Kingdom of Great Britain and Northern Ir...        94958.5          750
Singapore                                                 91391.0           41
Norway                                                    89439.0           88
Canada                                                    87550.0          492

In [72]:
# convert country statistics index to columns
country_stats = country_stats.reset_index()

# export country salary statistics to CSV
country_stats.to_csv(
    'salary_by_country_filtered_top10.csv',
    index=False
)

country_stats

,Country,median_salary,respondents
0,United States of America,150000.0,3126
1,Israel,142594.0,104
2,Switzerland,142592.0,240
3,Ireland,116015.0,74
4,Denmark,98289.0,120
5,Australia,97514.0,307
6,United Kingdom of Great Britain and Northern I...,94958.5,750
7,Singapore,91391.0,41
8,Norway,89439.0,88
9,Canada,87550.0,492

In [73]:
# count respondents by work format

remote_summary = df['RemoteWork'].value_counts(dropna=False)

print(remote_summary)

RemoteWork
NaN                                                                             15411
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [74]:
# count respondents by work format
remote_summary_clean = df['RemoteWork'].dropna().value_counts()

print(remote_summary_clean)

RemoteWork
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [75]:
# convert work format summary to table format
remote_chart = remote_summary_clean.reset_index()

# rename columns for dashboard use
remote_chart.columns = ['Work_Format', 'Respondents']

# simplify work format labels
remote_chart['Work_Format'] = remote_chart['Work_Format'].replace({
    'Hybrid (some remote, leans heavy to in-person)': 'Hybrid Remote',
    'Hybrid (some in-person, leans heavy to flexibility)': 'Hybrid Flexible',
    'Your choice (very flexible, you can come in when you want or just as needed)': 'Flexible Choice'
})

print(remote_chart)

       Work_Format  Respondents
0           Remote        10931
1    Hybrid Remote         6732
2        In-person         6042
3  Hybrid Flexible         5831
4  Flexible Choice         4244

In [76]:
# export remote work summary to CSV
remote_chart.to_csv('remote_work_analysis.csv', index=False)